/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 showroom2.glb 
Author: Polsaris (https://sketchfab.com/polsaris)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/car-showroom-1-40b0ae06eb8343e5bacf34e04fcfff73
Title: Car-Showroom 1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Showroom2(props) {
  const { nodes, materials } = useGLTF('/models/showroom2.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.837}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.236, 0]} scale={0.384}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials['Material.010']}
            />
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials['Material.011']}
            />
            <mesh
              geometry={nodes.Object_6.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Object_7.geometry}
              material={materials['Material.012']}
            />
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials['Material.004']}
            />
          </group>
          <group position={[-0.021, 4.779, 5.717]}>
            <mesh
              geometry={nodes.Object_30.geometry}
              material={materials['Material.007']}
            />
            <mesh
              geometry={nodes.Object_31.geometry}
              material={materials['Material.015']}
            />
          </group>
          <group
            position={[1.976, -0.195, 1.57]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[0.129, 0.189, 0.162]}
          >
            <mesh
              geometry={nodes.Object_33.geometry}
              material={materials['Material.005']}
            />
            <mesh
              geometry={nodes.Object_34.geometry}
              material={materials.Textur}
            />
          </group>
          <group position={[0, 4.015, 0]}>
            <mesh
              geometry={nodes.Object_40.geometry}
              material={materials['Material.003']}
            />
            <mesh
              geometry={nodes.Object_41.geometry}
              material={materials['Material.014']}
            />
          </group>
          <group position={[0, 2.933, -13.501]} rotation={[0.216, 0, 0]}>
            <mesh
              geometry={nodes.Object_45.geometry}
              material={materials['Material.017']}
            />
            <mesh
              geometry={nodes.Object_46.geometry}
              material={materials['Material.018']}
            />
          </group>
          <group
            position={[0, -0.038, 0]}
            rotation={[0, 0, -Math.PI]}
            scale={[0.272, 0.272, 0.394]}
          >
            <mesh
              geometry={nodes.Object_48.geometry}
              material={materials['Material.013']}
            />
            <mesh
              geometry={nodes.Object_49.geometry}
              material={materials['Material.013']}
            />
            <mesh
              geometry={nodes.Object_50.geometry}
              material={materials['Material.013']}
            />
            <mesh
              geometry={nodes.Object_51.geometry}
              material={materials['Material.013']}
            />
            <mesh
              geometry={nodes.Object_52.geometry}
              material={materials['Material.013']}
            />
            <mesh
              geometry={nodes.Object_53.geometry}
              material={materials['Material.013']}
            />
            <mesh
              geometry={nodes.Object_54.geometry}
              material={materials['Material.013']}
            />
            <mesh
              geometry={nodes.Object_55.geometry}
              material={materials['Material.013']}
            />
            <mesh
              geometry={nodes.Object_56.geometry}
              material={materials['Material.013']}
            />
            <mesh
              geometry={nodes.Object_57.geometry}
              material={materials['Material.013']}
            />
            <mesh
              geometry={nodes.Object_58.geometry}
              material={materials['Material.013']}
            />
            <mesh
              geometry={nodes.Object_59.geometry}
              material={materials['Material.013']}
            />
            <mesh
              geometry={nodes.Object_60.geometry}
              material={materials['Material.013']}
            />
          </group>
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials['Material.008']}
            position={[-0.023, 0.534, -13.953]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[1, 1, 2.915]}
          />
          <mesh
            geometry={nodes.Object_12.geometry}
            material={materials['Material.008']}
            position={[-0.023, 2.544, -13.953]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[1, 1, 2.915]}
          />
          <mesh
            geometry={nodes.Object_14.geometry}
            material={materials['Material.008']}
            position={[-0.023, 4.579, -13.953]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[1, 1, 2.915]}
          />
          <mesh
            geometry={nodes.Object_16.geometry}
            material={materials['Material.019']}
            position={[6.147, 5.092, 0.116]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[1, 1, 5.452]}
          />
          <mesh
            geometry={nodes.Object_18.geometry}
            material={materials['Material.008']}
            position={[7.311, 4.566, 0.116]}
            scale={[1, 0.985, 5.452]}
          />
          <mesh
            geometry={nodes.Object_20.geometry}
            material={materials['Material.008']}
            position={[7.311, 2.562, 0.125]}
            scale={[1, 0.985, 5.452]}
          />
          <mesh
            geometry={nodes.Object_22.geometry}
            material={materials['Material.008']}
            position={[7.311, 0.56, 0.116]}
            scale={[1, 0.985, 5.452]}
          />
          <mesh
            geometry={nodes.Object_24.geometry}
            material={materials['Material.008']}
            position={[-7.35, 4.566, 0.116]}
            scale={[1, 0.985, 5.452]}
          />
          <mesh
            geometry={nodes.Object_26.geometry}
            material={materials['Material.008']}
            position={[-7.35, 2.562, 0.125]}
            scale={[1, 0.985, 5.452]}
          />
          <mesh
            geometry={nodes.Object_28.geometry}
            material={materials['Material.008']}
            position={[-7.35, 0.56, 0.116]}
            scale={[1, 0.985, 5.452]}
          />
          <mesh
            geometry={nodes.Object_36.geometry}
            material={materials['Material.005']}
          />
          <mesh
            geometry={nodes.Object_37.geometry}
            material={materials['Material.015']}
          />
          <mesh
            geometry={nodes.Object_38.geometry}
            material={materials['Material.016']}
          />
          <mesh
            geometry={nodes.Object_43.geometry}
            material={materials['Material.020']}
            position={[0, -0.378, 0]}
            scale={[8.454, 8.454, 14.395]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/showroom2.glb')
