/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 road.glb -o Showroom2.jsx 
Author: Miguel-Angel (https://sketchfab.com/Miguel-Angel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/road-basic-maker-f79cd94fb9664064bb4414c4ee590875
Title: Road Basic Maker
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Showroom2(props) {
  const { nodes, materials } = useGLTF('/models/showroom2.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials['Material.005']}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials['Material.006']}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials['Material.007']}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials['Material.008']}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials['Material.009']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/showroom2.glb')
