/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 showroom.glb 
Author: Polsaris (https://sketchfab.com/polsaris)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/car-showroom-2-e7a3497e8a7c487e906b2d8814b018f0
Title: Car-Showroom 2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Showroom(props) {
  const { nodes, materials } = useGLTF('/models/showroom.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={[13.292, 10.539, 13.292]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Light} />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.Metallic_Dark_Grey}
        />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Wall} />
      </group>
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials['Material.006']}
        position={[0, 0.009, 0]}
        scale={14.311}
      />
    </group>
  )
}

useGLTF.preload('/models/showroom.glb')
