/* eslint-disable react/prop-types */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 porsche_964.glb -o cars.jsx 
Author: All-Wide (https://sketchfab.com/dsm350)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-porsche-964-wide-body-2554786e72b14c589ea2098a3bad1525
Title: Low poly Porsche 964 Wide Body
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Car({ rotationY }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/car/porsche_964.glb')
  return (
    <group
      ref={group}
      dispose={null}
      scale={0.6}
      position={[-1, 0.1, -1]}
      rotation={[0, rotationY, 0]}
    >
      <group
        position={[-0.675, 0.477, 1.817]}
        rotation={[1.58, 0, 0]}
        scale={0.254}
      >
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials['Material.007']}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials['0_0_0_2.002']}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials.Material}
        />
      </group>
      <group
        position={[-0.675, 0.477, 1.817]}
        rotation={[1.58, 0, 0]}
        scale={0.254}
      >
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Object_28.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials['16_24_240_241.013']}
        />
        <mesh
          geometry={nodes.Object_32.geometry}
          material={materials['0_0_0_4.002']}
        />
        <mesh
          geometry={nodes.Object_34.geometry}
          material={materials['Material.006']}
        />
        <mesh
          geometry={nodes.Object_36.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Object_38.geometry}
          material={materials['16_24_240_242.002']}
        />
        <mesh
          geometry={nodes.Object_40.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Object_42.geometry}
          material={materials.Material}
        />
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Material}
        position={[-0.675, 0.477, 1.817]}
        rotation={[1.58, 0, 0]}
        scale={0.254}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials['16_24_240_241.012']}
        position={[-0.675, 0.477, 1.817]}
        rotation={[1.58, 0, 0]}
        scale={0.254}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.Chocofur_Free_Car_02_Glass_01}
        position={[-0.675, 0.477, 1.817]}
        rotation={[1.58, 0, 0]}
        scale={0.254}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials['16_24_240_241.016']}
        position={[-0.675, 0.477, 1.817]}
        rotation={[1.58, 0, 0]}
        scale={0.254}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials.Material}
        position={[-0.675, 0.477, 1.817]}
        rotation={[1.58, 0, 0]}
        scale={0.254}
      />
      <mesh
        geometry={nodes.Object_24.geometry}
        material={materials['16_24_240_241.016']}
        position={[-0.675, 0.458, 1.167]}
        rotation={[1.58, 0, 0]}
        scale={0.282}
      />
      <mesh
        geometry={nodes.Object_44.geometry}
        material={materials['Material.003']}
        position={[1.378, 0.665, -0.895]}
        scale={2.227}
      />
      <mesh
        geometry={nodes.Object_46.geometry}
        material={materials['Apollo-balanced.001']}
        position={[1.177, 0.649, -0.913]}
        rotation={[0, 0, -1.592]}
        scale={0.756}
      />
      <mesh
        geometry={nodes.Object_48.geometry}
        material={materials['Material.020']}
        position={[1.707, 0.661, -0.903]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[3.534, 2.564, 2.564]}
      />
      <mesh
        geometry={nodes.Object_50.geometry}
        material={materials['Material.003']}
        position={[1.263, 0.665, 4.997]}
        scale={2.227}
      />
      <mesh
        geometry={nodes.Object_52.geometry}
        material={materials['Apollo-balanced.001']}
        position={[1.062, 0.649, 4.979]}
        rotation={[0, 0, -1.592]}
        scale={0.756}
      />
      <mesh
        geometry={nodes.Object_54.geometry}
        material={materials['Material.020']}
        position={[1.592, 0.661, 4.989]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[3.534, 2.564, 2.564]}
      />
      <mesh
        geometry={nodes.Object_56.geometry}
        material={materials['Material.003']}
        position={[-2.612, 0.658, 4.983]}
        rotation={[0, 0, 3.121]}
        scale={2.227}
      />
      <mesh
        geometry={nodes.Object_58.geometry}
        material={materials['Apollo-balanced.001']}
        position={[-2.411, 0.67, 4.965]}
        rotation={[0, 0, 1.529]}
        scale={0.756}
      />
      <mesh
        geometry={nodes.Object_60.geometry}
        material={materials['Material.020']}
        position={[-2.941, 0.669, 4.975]}
        rotation={[-Math.PI / 2, 0.021, -Math.PI]}
        scale={[3.534, 2.564, 2.564]}
      />
      <mesh
        geometry={nodes.Object_62.geometry}
        material={materials['Material.003']}
        position={[-2.756, 0.664, -0.908]}
        rotation={[0, 0, 3.121]}
        scale={2.227}
      />
      <mesh
        geometry={nodes.Object_64.geometry}
        material={materials['Apollo-balanced.001']}
        position={[-2.556, 0.676, -0.926]}
        rotation={[0, 0, 1.529]}
        scale={0.756}
      />
      <mesh
        geometry={nodes.Object_66.geometry}
        material={materials['Material.020']}
        position={[-3.085, 0.674, -0.915]}
        rotation={[-Math.PI / 2, 0.021, -Math.PI]}
        scale={[3.534, 2.564, 2.564]}
      />
    </group>
  )
}

useGLTF.preload('/models/car/porsche_964.glb')
